version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s %(name)s:%(lineno)d %(levelname)s %(message)s"
        datefmt: '%Y-%m-%dT%H:%M:%S'
    error:
        format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
        datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
#        stream: ext://sys.stdout

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET #WARNING #NOTSET
    handlers: [console, error_file_handler]

loggers:
    __main__:
        level: INFO
        propogate: yes

    lifeskills:
        level: INFO
        propogate: yes

    lifeskills.client:
        level: DEBUG
